# Generated by Django 3.2.8 on 2021-12-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pc',
        ),
    ]
