# Generated by Django 3.2.8 on 2021-12-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Host', '0002_delete_pc'),
    ]

    operations = [
        migrations.CreateModel(
            name='pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('cpu_num', models.CharField(max_length=5)),
                ('cpu_percent', models.CharField(max_length=30)),
                ('memory_total', models.CharField(max_length=30)),
                ('memory_ava', models.CharField(max_length=30)),
                ('memory_per', models.CharField(max_length=30)),
                ('disk_total', models.CharField(max_length=30)),
                ('disk_free', models.CharField(max_length=30)),
                ('net_sent', models.CharField(max_length=30)),
                ('net_rec', models.CharField(max_length=30)),
            ],
        ),
    ]
