# Generated by Django 3.2.8 on 2021-12-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0003_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='time',
            field=models.TimeField(default='10:12'),
        ),
    ]
