# Generated by Django 3.2.8 on 2021-12-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0005_alter_pc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
